---
- hosts: all
  become: yes

  pre_tasks:
    - import_tasks: tasks/users.yml
      tags: users

  roles:
    - role: bertvv.samba
      tags:
        - samba

    - role: geerlingguy.docker
      tags:
        - docker

    - role: geerlingguy.security
      tags:
        - security

    ###
    ### Ansible-NAS Roles
    ###
    - role: ansible-nas-general
      tags:
        - ansible-nas-general

    - role: ansible-nas-docker
      tags:
        - ansible-nas-docker
    ###
    ### Applications
    ###

    - role: bitwarden
      tags:
        - bitwarden
      when: (bitwarden_enabled | default(False))

    - role: copticdrome
      tags:
        - copticdrome
      when: (copticdrome_enabled | default(False))

    - role: filebrowser
      tags:
        - filebrowser
      when: (filebrowser_enabled | default(False))

    - role: firefly
      tags:
        - firefly
      when: (firefly_enabled | default(False))

    - role: flaresolverr
      tags:
        - flaresolverr
      when: (flaresolverr_enabled | default(False))

    - role: gitlab
      tags:
        - gitlab
      when: (gitlab_enabled | default(False))

    - role: heimdall
      tags:
        - heimdall
      when: (heimdall_enabled | default(False))

    - role: jackett
      tags:
        - jackett
      when: (jackett_enabled | default(False))

    - role: jellyfin
      tags:
        - jellyfin
      when: (jellyfin_enabled | default(False))

    - role: minecraft
      tags:
        - minecraft
      when: (minecraft_enabled | default(False))

    - role: navidrome
      tags:
        - navidrome
      when: (navidrome_enabled | default(False))

    - role: nextcloud
      tags:
        - nextcloud
      when: (nextcloud_enabled | default(False))

    - role: librespeed
      tags:
        - librespeed
      when: (librespeed_enabled | default(False))

    - role: plex
      tags:
        - plex
      when: (plex_enabled | default(False))

    - role: portainer
      tags:
        - portainer
      when: (portainer_enabled | default(False))

    - role: radarr
      tags:
        - radarr
      when: (radarr_enabled | default(False))

    - role: sonarr
      tags:
        - sonarr
      when: (sonarr_enabled | default(False))

    - role: sonarra
      tags:
        - sonarra
      when: (sonarra_enabled | default(False))

    - role: sftp
      tags:
        - sftp
      when: (sftp_enabled | default(False))

    - role: traefik
      tags:
        - traefik
      when: (traefik_enabled | default(False))
    - role: uptime-kuma
      tags:
        - uptime_kuma
      when: (uptime_kuma_enabled | default(False))

    - role: watchtower
      tags:
        - watchtower
      when: (watchtower_enabled | default(False))

    - role: transmission-with-openvpn
      tags:
        - servarr
        - transmission
      when: (transmission_enabled | default(False))
