---
# Here is my variables for this playbook

## Packages that I want to install
packages:
  - rsync
  - ranger
  - git
  - neovim
  - vim
  - htop
  - neofetch
  - tmux
  - speedtest-cli
  - net-tools

ansible_nas_hostname: ubuntu-server
ansible_nas_timezone: Europe/Paris

transmission_enabled: true
bitwarden_enabled: false
copticdrome_enabled: false
flaresolverr_enabled: true
filebrowser_enabled: true
jackett_enabled: true
nextcloud_enabled: false
librespeed_enabled: true
jellyfin_enabled: false
portainer_enabled: true
traefik_enabled: true
heimdall_enabled: false
radarr_enabled: true
sonarr_enabled: true
sonarra_enabled: true
uptime_kuma_enabled: true
sftp_enabled: false
watchtower_enabled: true
plex_enabled: false
minecraft_enabled: false


sonarra_available_externally: "true"
sonarr_available_externally: "true"
radarr_available_externally: "true"

minecraft_available_externally: "true"
plex_available_externally: "true"
uptime_kuma_available_externally: "true"
librespeed_available_externally: "true"
portainer_available_externally: "true"
jellyfin_available_externally: "true"
filebrowser_available_externally: "true"
nextcloud_available_externally: "true"
bitwarden_available_externally: "true"

root_directory: /srv

personal_user: luffy
personal_group: luffy
personal_directory: "{{ root_directory}}/cyril"
personal_user_id: "1000"
personal_group_id: "1000"

ansible_nas_user: nasa
ansible_nas_group: nasa
ansible_nas_email: ghlcyril@gmail.com
ansible_nas_domain: cghali.fr
ansible_nas_user_id: "1013"
ansible_nas_group_id: "1013"
ansible_python_interpreter: /usr/bin/python3

samba_shares_root: "{{ root_directory}}/public"

downloads_root: "{{ samba_shares_root }}/downloads"
movies_root: "{{ samba_shares_root }}/movies"
anime_root: "{{ samba_shares_root }}/anime"
tv_root: "{{ samba_shares_root }}/tv"
music_root: "{{ samba_shares_root }}/music"
videos_root: "{{ samba_shares_root }}/videos"
coptic_root: "{{ samba_shares_root }}/coptic"
podcasts_root: "{{ samba_shares_root }}/podcasts"
books_root: "{{ samba_shares_root }}/books"
audiobooks_root: "{{ samba_shares_root }}/audiobooks"
comics_root: "{{ samba_shares_root }}/comics"
photos_root: "{{ samba_shares_root }}/photos"
samba_server_string: SMB Server
samba_shares:
  - name: downloads
    comment: "Stuff downloaded"
    guest_ok: yes
    public: yes
    writable: yes
    browseable: yes
    path: "{{ downloads_root }}"

  - name: movies
    comment: "Movies"
    guest_ok: yes
    public: yes
    writable: yes
    browseable: yes
    path: "{{ movies_root }}"

  - name: tv
    comment: "TV Episodes"
    guest_ok: yes
    public: yes
    writable: yes
    browseable: yes
    path: "{{ tv_root }}"

  - name: anime
    comment: "Anime Episodes"
    guest_ok: yes
    public: yes
    writable: yes
    browseable: yes
    path: "{{ anime_root }}"

  - name: music
    comment: "Music"
    guest_ok: yes
    public: yes
    writable: yes
    browseable: yes
    path: "{{ music_root }}"

  - name: podcasts
    comment: "Podcasts"
    guest_ok: yes
    public: yes
    writable: yes
    browseable: yes
    path: "{{ podcasts_root }}"

  - name: dump
    comment: "File dump"
    guest_ok: yes
    public: yes
    writable: yes
    browseable: yes
    path: "{{  samba_shares_root  }}/dump"

  - name: games
    comment: "Games"
    guest_ok: yes
    public: yes
    writable: yes
    browseable: yes
    path: "{{ samba_shares_root }}/games"

  - name: photos
    comment: "Pictures"
    guest_ok: yes
    public: yes
    writable: yes
    browseable: yes
    path: "{{ photos_root }}"

  - name: books
    comment: "Books"
    guest_ok: yes
    public: yes
    writable: yes
    browseable: yes
    path: "{{ books_root }}"

  - name: audiobooks
    comment: "Audiobooks"
    guest_ok: yes
    public: yes
    writable: yes
    browsable: yes
    path: "{{ samba_shares_root }}/audiobooks"

  - name: comics
    comment: "Comics"
    guest_ok: yes
    public: yes
    writable: yes
    browseable: yes
    path: "{{ comics_root }}"

  # - name: coptic
  #   comment: 'Coptic'
  #   guest_ok: yes
  #   public: yes
  #   writable: yes
  #   browseable: yes
  #   path: '{{ coptic_root }}'

# Seems to break browsing of the \\server-name shares root when enabled
samba_mitigate_cve_2017_7494: false
samba_apple_extensions: yes
samba_guest_account: nasa
samba_map_to_guest: Bad Password

# The NetBIOS hostname used by Samba on your network
samba_netbios_name: "{{ ansible_nas_hostname }}"

openvpn_provider: "NORDVPN"
