---
templateservice_enabled: false
templateservice_available_externally: "false"

# directories
templateservice_data_directory: "{{ docker_home }}/templateservice/config"

# uid / gid
templateservice_user_id: "{{ ansible_nas_user_id }}"
templateservice_group_id: "{{ ansible_nas_group_id }}"

# network
templateservice_port: "8990"
templateservice_hostname: "templateservice"
