---
sonarr_enabled: false
sonarr_available_externally: "false"

# directories
sonarr_data_directory: "{{ docker_home }}/sonarr/config"
sonarr_tv_directory: "{{ tv_root }}"
sonarr_download_directory: "{{ downloads_root }}"

# uid / gid
sonarr_user_id: "{{ ansible_nas_user_id }}"
sonarr_group_id: "{{ ansible_nas_group_id }}"

# network
sonarr_port: "8989"
sonarr_hostname: "sonarr"
